[nrf fromtree] tfm: Fix undefined reference to 'end' ...
when disabling secure output

Fix undefined reference to 'end' when disabling secure output from the
TF-M image.

When secure output is disabled the printf function is not overriden
in TF-M and the libc variant has references to heap functions.
Make sure that the printf function is overriden for this case also and
drop the output message.

NCSDK-22818

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>
(cherry picked from commit ff40315812bf2a738177c5facd25bbfd39c0e6ca)